// Code generated by MockGen. DO NOT EDIT.
// Source: ./relayer/message/handler.go
//
// Generated by this command:
//
//	mockgen -source=./relayer/message/handler.go -destination=./mock/message.go -package mock
//
// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	message "github.com/sygmaprotocol/sygma-core/relayer/message"
	proposal "github.com/sygmaprotocol/sygma-core/relayer/proposal"
	gomock "go.uber.org/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// HandleMessage mocks base method.
func (m_2 *MockHandler) HandleMessage(m *message.Message) (*proposal.Proposal, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "HandleMessage", m)
	ret0, _ := ret[0].(*proposal.Proposal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleMessage indicates an expected call of HandleMessage.
func (mr *MockHandlerMockRecorder) HandleMessage(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMessage", reflect.TypeOf((*MockHandler)(nil).HandleMessage), m)
}
